### ISSUE TITLE
i got error to run msmbuilder tICA 

### ISSUE THREAD

**Issue by gsuchunli** [msmbuilder/msmbuilder#1029]
Please see below:
msmb tICA -i scaled_rmsd.h5 --out tica_model.pkl --transformed tica_trajs.h5 --n_components 4 --lag_time 100 

tICA(commute_mapping=False, kinetic_mapping=False, lag_time=100,
   n_components=4, shrinkage=None)
Fitting model...
*********
*RESULTS*
*********
An unexpected error has occurred with MSMBuilder (version 3.8.0), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "//anaconda/bin/msmb", line 6, in <module>
    sys.exit(msmbuilder.scripts.msmb.main())
  File "//anaconda/lib/python3.5/site-packages/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "//anaconda/lib/python3.5/site-packages/msmbuilder/cmdline.py", line 464, in start
    instance.start()
  File "//anaconda/lib/python3.5/site-packages/msmbuilder/commands/fit_transform.py", line 73, in start
    print(self.instance.summarize())
  File "//anaconda/lib/python3.5/site-packages/msmbuilder/decomposition/tica.py", line 489, in summarize
    timescales=self.timescales_[:5], eigenvalues=self.eigenvalues_[:5])
  File "//anaconda/lib/python3.5/site-packages/msmbuilder/decomposition/tica.py", line 221, in timescales_
    self._solve()
  File "//anaconda/lib/python3.5/site-packages/msmbuilder/decomposition/tica.py", line 189, in _solve
    eigvals=(self.n_features-self.n_components, self.n_features-1))
  File "//anaconda/lib/python3.5/site-packages/scipy/linalg/decomp.py", line 320, in eigh
    'Valid range is [%s,%s]' % (0, a1.shape[0]-1))
ValueError: The eigenvalue range specified is not valid.
Valid range is [0,0]
Closing remaining open files:scaled_rmsd.h5...done

Thanks,

**Comment by msultan** [comment]
Do you only have one feature? Aka scaled RMSD to a single structure? tICA cant be done on a single feature. Please try a different featurization scheme or calculating RMSD to a bunch of different pdbs as your input features.

**Comment by msultan** [comment]
Hi, can i close this now?
