### ISSUE TITLE
Import issue after installation

### ISSUE THREAD

**Issue by girodat** [msmbuilder/msmbuilder#1106]
I have been encountering a problem with msmbuilder after I installed it. When I try to run msmb -h I get the error:
```
/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
Traceback (most recent call last):
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/bin/msmb", line 4, in <module>
    import msmbuilder.scripts.msmb
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/commands/__init__.py", line 5, in <module>
    from .example_datasets import AlanineDipeptideDatasetCommand
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/commands/example_datasets.py", line 4, in <module>
    from ..example_datasets import (AlanineDipeptide, DoubleWell, QuadWell, FsPeptide,
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/example_datasets/__init__.py", line 3, in <module>
    from .brownian1d import DoubleWell, QuadWell
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/example_datasets/brownian1d.py", line 17, in <module>
    from ..msm import _solve_msm_eigensystem
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/msm/__init__.py", line 2, in <module>
    from .core import *
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/msm/core.py", line 17, in <module>
    from ..utils import list_of_1d
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/utils/__init__.py", line 4, in <module>
    from .param_sweep import *
  File "/lustre/scratch3/turquoise/dgirodat/conda_envs/msm2/lib/python2.7/site-packages/msmbuilder/utils/param_sweep.py", line 3, in <module>
    from sklearn.grid_search import ParameterGrid
ImportError: No module named grid_search
```

Any ideas as to what is going on?

**Comment by cxhernandez** [comment]
Yes. If you want msmbuilder to run properly with the current installation, you'll have to rollback `sklearn` to an earlier version:

```
conda install scikit-learn==0.18.1
```

@msmbuilder/developers: We should replace with with `from sklearn.model_selection import GridSearchCV`, since the `grid_search` has been deprecated.

**Comment by girodat** [comment]
Thank you for the information I was able to install the older version of
scikit-learn. I now have the error of

Traceback (most recent call last):
  File "gather-metadata.py", line 10, in <module>
       from msmbuilder.io import gather_metadata, save_meta,
NumberedRunsParser
  ImportError: No module named 'msmbuilder.io'

I was wondering if you have seen this before?

the script I am trying to run is
"""Find trajectories and associated metadata
 msmbuilder autogenerated template version 2
created 2018-10-22T14:39:54.338193
please cite msmbuilder in any publications

 """  from msmbuilder.io import gather_metadata, save_meta,
NumberedRunsParser
 ## Construct and save the dataframe
parser = NumberedRunsParser(
     traj_fmt="trajectory-{run}.xtc",
     top_fn="top.pdb",
     step_ps=50,
)
meta = gather_metadata("trajs/*.xtc", parser)
 save_meta(meta)

Thank you

**Comment by girodat** [comment]
I believe I have solved the issue.

Thanks again for all of the help.
