### ISSUE TITLE
Memory issues in sample-ghmm

### ISSUE THREAD

**Issue by spetznova** [msmbuilder/msmbuilder#122]
I've been trying to use the following sample-ghmm command without success:

hmsm sample-ghmm  -i hmms.jsonlines_heavy --featurizer featurizer.heavy --dir /home/willf/Trajectories/ --top /home/willf/analysis/protein_common_res.pdb --ext lh5 --n-states 4 --lag-time 20 --n-per-state 100 -o samples_heavy_4_20.csv

I'm currently working with 1858 features, and the total size of the trajectories is 32GB.  Here is the error I get when I run it:
```
/home/willf/Installation/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py:382: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')
Traceback (most recent call last):
  File "/home/willf/Installation/anaconda/bin/hmsm", line 5, in <module>
    pkg_resources.run_script('mixtape==0.2', 'hmsm')
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/setuptools-3.1-py2.7.egg/pkg_resources.py", line 528, in run_script
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/setuptools-3.1-py2.7.egg/pkg_resources.py", line 1394, in run_script
  File "/biox3/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/hmsm", line 8, in <module>
    app.start()
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/mixtape/cmdline.py", line 232, in start
    instance.start()
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/mixtape/commands/sample.py", line 142, in start
    self.model['vars'][k], self.match_vars)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/mixtape/discrete_approx.py", line 163, in discrete_approx_mvn
    objective_and_grad, jac=True, x0=np.ones_like(moments), method='BFGS')
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 372, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 832, in _minimize_bfgs
    gfk = myfprime(x0)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 67, in derivative
    self(x, *args)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 59, in __call__
    fg = self.fun(x, *args)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/mixtape/discrete_approx.py", line 156, in objective_and_grad
    exp_term = np.sum(moment_contributions * (prob * np.exp(dot - dot_max)).reshape(-1, 1), axis=0)
MemoryError
Traceback (most recent call last):
  File "/home/willf/Installation/anaconda/bin/hmsm", line 5, in <module>
    pkg_resources.run_script('mixtape==0.2', 'hmsm')
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/setuptools-3.1-py2.7.egg/pkg_resources.py", line 528, in run_script
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/setuptools-3.1-py2.7.egg/pkg_resources.py", line 1394, in run_script
  File "/biox3/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/hmsm", line 8, in <module>
    app.start()
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/mixtape/cmdline.py", line 231, in start
    instance = klass(args)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mixtape-0.2-py2.7-linux-x86_64.egg/mixtape/commands/structures.py", line 67, in __init__
    self.top = md.load(args.top).topology
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 270, in load
    _assert_files_exist(filename_or_filenames)
  File "/home/willf/Installation/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 77, in _assert_files_exist
    raise IOError('No such file: %s' % fn)
IOError: No such file: protein_common_res.pdb
```
What do you recommend I do for fixing this issue?  Do you think this is a memory problem?

@msultan

**Comment by mpharrigan** [comment]
This command no longer exists
