### ISSUE TITLE
pip install msmbuilder fails

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#445]
We're missing the `MANIFEST.in` file I think. Will do 3.0.1.

```
$ pip install msmbuilder --upgrade --force
Collecting msmbuilder
  Downloading msmbuilder-3.0.0.tar.gz (162kB)
    100% |################################| 163kB 1.8MB/s
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-l543xc8a/msmbuilder/setup.py", line 18, in <module>
        from basesetup import write_version_py, CompilerDetection, check_dependencies
    ImportError: No module named 'basesetup'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-l543xc8a/msmbuilder/setup.py", line 18, in <module>

        from basesetup import write_version_py, CompilerDetection, check_dependencies

    ImportError: No module named 'basesetup'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-l543xc8a/msmbuilder
```

**Comment by rmcgibbo** [comment]
Fixed.
