### ISSUE TITLE
Tests often fail due to HTTP timeout when pulling from figshare

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#461]
This is happening frequently enough to kill a nontrivial fraction of the tests that get run on travis. Perhaps we should retry the request up to ~3 times or something.

Example:
```
ERROR: test suite for <module 'msmbuilder.tests.test_commands' from '/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/msmbuilder-3.1.0.dev0-py3.3-linux-x86_64.egg/msmbuilder/tests/test_commands.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/msmbuilder-3.1.0.dev0-py3.3-linux-x86_64.egg/msmbuilder/tests/test_commands.py", line 57, in setup_module
    fetch_alanine_dipeptide()
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/msmbuilder-3.1.0.dev0-py3.3-linux-x86_64.egg/msmbuilder/example_datasets/alanine_dipeptide.py", line 91, in fetch_alanine_dipeptide
    return AlanineDipeptide(data_home).get()
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/msmbuilder-3.1.0.dev0-py3.3-linux-x86_64.egg/msmbuilder/example_datasets/alanine_dipeptide.py", line 80, in get
    self.cache()
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/msmbuilder-3.1.0.dev0-py3.3-linux-x86_64.egg/msmbuilder/example_datasets/alanine_dipeptide.py", line 69, in cache
    fhandle = urlopen(DATA_URL)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/urllib/request.py", line 595, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Timeout
```

**Comment by kyleabeauchamp** [comment]
So this just happened to me when trying to work through the ALA HMM MSM example as well.  I re-tried and it worked the second time.  Probably worth a retry as a way to avoid sending HTTP errors to beginners.
