### ISSUE TITLE
msmb ConvertChunkedProject error

### ISSUE THREAD

**Issue by gfzhou** [msmbuilder/msmbuilder#483]
Hi Robert McGibbon,
I am using anaconda version of msmbuilder 3.0 and trying to convert the folding@home data to lh5 files. I have used the old version of msmbuilder a lot and I assume that msmb ConverChunkedProject is the new version of ConvertDataToHDF.py. I ran the command and got the following error.

$ msmb ConvertChunkedProject --no-discard-first --dry-run --outfmt lh5 --pattern 'frame*.xtc' -t p6383/Gen0_ready4fah.gro Converted6383 PROJ6383
An unexpected error has occurred with MSMBuilder (version 3.0.0), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/Users/tud51931/anaconda/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/Users/tud51931/anaconda/lib/python2.7/site-packages/msmbuilder-3.0.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/scripts/msmb.py", line 27, in main
    app = MSMBuilderApp(name='MSMBuilder', description=__doc__)
  File "/Users/tud51931/anaconda/lib/python2.7/site-packages/msmbuilder-3.0.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/cmdline.py", line 403, in __init__
    self.args = self.parser.parse_args(argv)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1921, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1898, in consume_positionals
    take_action(action, args)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1096, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 1791, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 2231, in _get_values
    value = self._get_value(action, arg_string)
  File "/Users/tud51931/anaconda/lib/python2.7/argparse.py", line 2260, in _get_value
    result = type_func(arg_string)
  File "/Users/tud51931/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 133, in _parse_topology
    topology = load_gro(top).topology
  File "/Users/tud51931/anaconda/lib/python2.7/site-packages/mdtraj/formats/gro.py", line 96, in load_gro
    coordinates = in_units_of(coordinates, f.distance_unit, Trajectory._distance_unit, inplace=True)
NameError: global name 'in_units_of' is not defined

Thanks,
Guangfeng Zhou

**Comment by kyleabeauchamp** [comment]
Don't use lh5 files for MSMBuilder3.  With MSMBuilder3 and MDTraj, there's really no need to use the old lh5 format.

**Comment by kyleabeauchamp** [comment]
It looks like this might be a bug in MDTraj, however, so if you're very interested see if you can reproduce the bug using `mdtraj.load()`

**Comment by gfzhou** [comment]
Thanks Kyle. 
I know where I did wrong, I accidentally using .gro file as the topology file when loading the trajectories and the mdtraj doesn't support .gro file format. I think that adding a top format checking function can fix this bug.

**Comment by rmcgibbo** [comment]
From git-blame, it looks like @synapticarbors fixed this bug in mdtraj, and it was part of mdtraj 1.3.0 (latest release).

**Comment by gfzhou** [comment]
Great ! Thanks.
