### ISSUE TITLE
minor install issue

### ISSUE THREAD

**Issue by evanfeinberg** [msmbuilder/msmbuilder#529]
Hey MSMBuilder Devs,

Just found what could be a minor installation issue. After installing the latest iteration of anaconda, and then using:

conda install -c https://conda.binstar.org/omnia msmbuilder

to install msmbuilder, which worked without a hitch, I the ran: 

msmb -h

and was returned the following issue: 

"dn0a22f483:~ evan$ msmb -h
Traceback (most recent call last):
  File "/Users/evan/anaconda/bin/msmb", line 4, in <module>
    from msmbuilder.scripts.msmb import main
  File "/Users/evan/anaconda/lib/python2.7/site-packages/msmbuilder-3.1.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/Users/evan/anaconda/lib/python2.7/site-packages/msmbuilder-3.1.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/commands/__init__.py", line 6, in <module>
    from .fit_transform import KMeansCommand, KCentersCommand
  File "/Users/evan/anaconda/lib/python2.7/site-packages/msmbuilder-3.1.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/commands/fit_transform.py", line 18, in <module>
    from ..decomposition import tICA, PCA, SparseTICA
  File "/Users/evan/anaconda/lib/python2.7/site-packages/msmbuilder-3.1.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/decomposition/__init__.py", line 2, in <module>
    from .tica import tICA
  File "/Users/evan/anaconda/lib/python2.7/site-packages/msmbuilder-3.1.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/decomposition/tica.py", line 16, in <module>
    from sklearn.utils import array2d
ImportError: cannot import name array2d" 

I then downgraded SciKit with the following command thanks to Carlos's help: 

conda install scikit-learn==0.15.2

This seemed to fix the issue. So it seems the latest version of scikit-learn has this compatibility issue. 

Cheers,
Evan

**Comment by jchodera** [comment]
The [omnia recipe for msmbuilder](https://github.com/omnia-md/conda-recipes/blob/master/msmbuilder/meta.yaml#L17-L34) doesn't seem to specify any specific software versions (presumably for maximum flexibility in trying to avoid dependency conflicts?).  May need to specify a specific range of scikit-learn packages to work around this, though.

**Comment by kyleabeauchamp** [comment]
I imagine we'll probably just roll out a new release soonish, as we've already fixed this bug in the latest master.

**Comment by evanfeinberg** [comment]
Great, thanks for the quick response everyone!

**Comment by mpharrigan** [comment]
cc #525 #528
