### ISSUE TITLE
"top" argument and SuperposeFeaturizer 

### ISSUE THREAD

**Issue by ekcarter** [msmbuilder/msmbuilder#555]
Dear MSMbuilders,

I have been experimenting with your command line interface (version 3.2.0 devel, updated yesterday).  The SuperposeFeaturizer fails with the following traceback:
```
Traceback (most recent call last):
  File "/home/ekcarter/anaconda3/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/home/ekcarter/anaconda3/lib/python3.4/site-packages/msmbuilder-3.2.0.dev0-py3.4-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/home/ekcarter/anaconda3/lib/python3.4/site-packages/msmbuilder-3.2.0.dev0-py3.4-linux-x86_64.egg/msmbuilder/cmdline.py", line 438, in start
    instance = klass(args)
  File "/home/ekcarter/anaconda3/lib/python3.4/site-packages/msmbuilder-3.2.0.dev0-py3.4-linux-x86_64.egg/msmbuilder/cmdline.py", line 280, in __init__
    kwargs[k] = getattr(self, '_%s_type' % k)(v)
  File "/home/ekcarter/anaconda3/lib/python3.4/site-packages/msmbuilder-3.2.0.dev0-py3.4-linux-x86_64.egg/msmbuilder/commands/featurizer.py", line 88, in _reference_traj_type
    return md.load(fn)
  File "/home/ekcarter/anaconda3/lib/python3.4/site-packages/mdtraj-1.3.0-py3.4-linux-x86_64.egg/mdtraj/core/trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "dcd.pyx", line 127, in dcd.load_dcd (mdtraj/formats/dcd/dcd.c:1770)
ValueError: "top" argument is required for load_dcdmsmb SuperposeFeaturizer --out ./superpose_test --stride 100 --top ../3U5Z_DNA_only.prmtop --trjs "../traj/*.dcd" --atom_indices AtomIndices2.txt --reference_traj ../traj/traj01.dcd --superpose_atom_indices SuperposeIndices.txt 
```
These are the command line arguments I used:
```
msmb SuperposeFeaturizer --out ./superpose_test --stride 100 --top ../3U5Z_DNA_only.prmtop --trjs "../traj/*.dcd" --atom_indices AtomIndices2.txt --reference_traj ../traj/traj01.dcd --superpose_atom_indices SuperposeIndices.txt 
```
Any help would be great!

Thanks,
EKC

**Comment by rmcgibbo** [comment]
This looks like a bug here, https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/commands/featurizer.py#L102-L103,
where the topology isn't getting passed through.

**Comment by ekcarter** [comment]
Is there something I can do to fix this?

**Comment by rmcgibbo** [comment]
You're welcome to edit the code and file a pull request to fix the bug. Probably this will require using the same code snippet from https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/commands/featurizer.py#L53-L57, and then calling `md.load()` with a value for the `top` keyword argument.

If you're not familiar with git/github, there are some good tutorials and guides, such as https://guides.github.com/activities/contributing-to-open-source/.

Or myself or one of the other developers will fix this shortly.

**Comment by ekcarter** [comment]
I am new to GitHub and will take a look at the tutorials guides you recommend. Just a final point of clarification, if I use another featurizer with similar input (ie AtomPairsFeaturizer) I have no problem with the --top flag. I am not sure it is a path definition problem.
