### ISSUE TITLE
Get Appveyor working

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#574]
The reason why it's not straightforward is they only have the "express" versions of vc++2010 and 2008, which don't have normal x64 support

**Comment by rmcgibbo** [comment]
Ideas:
 - Maybe we find another python project that is successfully using windows x64 on appveyor?
 - Maybe we can ask the people at Appveyor to install the right compilers?

**Comment by rmcgibbo** [comment]
It looks to me like https://github.com/ogrisel/python-appveyor-demo is getting x64 working

**Comment by mpharrigan** [comment]
re (2): I don't think they'd be very keen

http://help.appveyor.com/discussions/problems/466-no-support-for-visual-studio-c-2008-and-2010
^^ very relevant

http://poquitopicante.blogspot.com/2014/04/fix-vcvarsallbat-to-install-python-27.html
^^ I think a potential fix

I'm trying to reproduce the problem on a VM because it takes > 30 minutes for an appveyor build to even start

**Comment by mpharrigan** [comment]
```
C:\miniconda3_x64\conda-bld\work>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
```

The relevant error message

**Comment by mpharrigan** [comment]
I think the express versions of visual studio don't put the `vcvarsallxx.bat` files in the same place

**Comment by rmcgibbo** [comment]
Do you have any idea of ogrisel's example is applicable?

**Comment by mpharrigan** [comment]
Yeah that would probably work. I think that's essentially what we have now. It looks overengineered

http://stackoverflow.com/a/13751649

suggests that just finding the right vcvarsall can work

**Comment by rmcgibbo** [comment]
Is the project status on https://ci.appveyor.com/project/rmcgibbo/msmbuilder/history accurate? It suggests to me that only py27-x64 is broken, and the error message is `Error: Unsatisfiable package specifications`.

**Comment by mpharrigan** [comment]
Yeah it looks like the build actually is working (although tests aren't being run due to conda bug)

**Comment by rmcgibbo** [comment]
Is that the conda bug you fixed earlier, or something different?

**Comment by mpharrigan** [comment]
I fixed it upstream, and provided a work around in a branch that I haven't pr-ed yet.

The build's probably working now that I pushed all the dependency packages

**Comment by rmcgibbo** [comment]
Well a build is currently pending, so I guess we'll see https://ci.appveyor.com/project/rmcgibbo/msmbuilder

**Comment by mpharrigan** [comment]
see what?

**Comment by rmcgibbo** [comment]
> The build's probably working now

If the build is working now.

**Comment by mpharrigan** [comment]
*The build's probably [working as well as it is] because of ...

You can look at the previous appveyor build if you want to see if this one's going to succeed

**Comment by rmcgibbo** [comment]
Oh, I see.

**Comment by rmcgibbo** [comment]
I don't really know what's going on.

Do you have a good idea why the py27-x64 build is currently failing? Is it a bug in conda? Is it something we can either fix or work around?

**Comment by mpharrigan** [comment]
Are there 64 bit builds of all the omnia packages?

**Comment by rmcgibbo** [comment]
So the latest errors are 

```
======================================================================
ERROR: msmbuilder.tests.test_dataset.test_union
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py2.7-win32.egg\msmbuilder\tests\test_dataset.py", line 197, in test_union
    np.testing.assert_array_almost_equal(np.sum(mds[1], axis=1), rs2)
  File "c:\python27_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py2.7-win32.egg\msmbuilder\tests\test_commands.py", line 71, in __exit__
    shutil.rmtree(self._tempdir)
  File "C:\Python27_32\envs\_test\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27_32\envs\_test\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\tmpook63u\\ds1.h5'
 
======================================================================
ERROR: msmbuilder.tests.test_workflows.test_workflow_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py2.7-win32.egg\msmbuilder\tests\test_workflows.py", line 32, in test_workflow_2
    subprocess.check_call(line.split())
  File "C:\Python27_32\envs\_test\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['msmb', 'GaussianHMM', '--inp', 'atom_pairs_tica.h5', '--out', 'hmm.pkl', '--n_states', '2']' returned non-zero exit status 255
 
----------------------------------------------------------------------
Ran 327 tests in 703.644s
 ```

**Comment by rmcgibbo** [comment]
and 

```
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\Scripts\msmb-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\scripts\msmb.py", line 28, in main
    app.start()
  File "C:\Python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cmdline.py", line 435, in start
    instance.start()
  File "C:\Python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\commands\fit_transform.py", line 58, in start
    self.instance.fit(inp_ds)
  File "C:\Python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\regularspatial.py", line 127, in fit
    MultiSequenceClusterMixin.fit(self, sequences)
  File "C:\Python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\base.py", line 48, in fit
    super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
  File "C:\Python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\regularspatial.py", line 74, in fit
    X, X[i], metric=self.metric, X_indices=np.array(cluster_ids))
  File "ibdistance\libdistance.pyx", line 176, in msmbuilder.libdistance.dist (msmbuilder/libdistance\libdistance.cpp:3334)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
ERROR
 
======================================================================
ERROR: msmbuilder.tests.test_clustering.test_regular_spatial_rmsd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_clustering.py", line 15, in test_regular_spatial_rmsd
    model.fit([trj])
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\regularspatial.py", line 127, in fit
    MultiSequenceClusterMixin.fit(self, sequences)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\base.py", line 48, in fit
    super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\regularspatial.py", line 74, in fit
    X, X[i], metric=self.metric, X_indices=np.array(cluster_ids))
  File "ibdistance\libdistance.pyx", line 176, in msmbuilder.libdistance.dist (msmbuilder/libdistance\libdistance.cpp:3334)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_clustering.test_regular_spatial
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_clustering.py", line 29, in test_regular_spatial
    model.fit([X])
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\regularspatial.py", line 127, in fit
    MultiSequenceClusterMixin.fit(self, sequences)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\base.py", line 48, in fit
    super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\regularspatial.py", line 74, in fit
    X, X[i], metric=self.metric, X_indices=np.array(cluster_ids))
  File "ibdistance\libdistance.pyx", line 176, in msmbuilder.libdistance.dist (msmbuilder/libdistance\libdistance.cpp:3334)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_dataset.test_union
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_dataset.py", line 197, in test_union
    np.testing.assert_array_almost_equal(np.sum(mds[1], axis=1), rs2)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_commands.py", line 71, in __exit__
    shutil.rmtree(self._tempdir)
  File "C:\Python34_64\envs\_test\lib\shutil.py", line 478, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34_64\envs\_test\lib\shutil.py", line 373, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python34_64\envs\_test\lib\shutil.py", line 371, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\tmptbe2cp15\\ds1.h5'
 
======================================================================
ERROR: msmbuilder.tests.test_kmedoids.test_inertia
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_kmedoids.py", line 20, in test_inertia
    km.fit(X)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\minibatchkmedoids.py", line 110, in fit
    dmat = libdistance.pdist(X, metric=self.metric, X_indices=minibatch_indices)
  File "ibdistance\libdistance.pyx", line 129, in msmbuilder.libdistance.pdist (msmbuilder/libdistance\libdistance.cpp:2826)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_kmedoids.test_obvious_clustering
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_kmedoids.py", line 33, in test_obvious_clustering
    k1 = _MiniBatchKMedoids(n_clusters=2, max_iter=5, random_state=0, batch_size=20).fit(X)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\minibatchkmedoids.py", line 110, in fit
    dmat = libdistance.pdist(X, metric=self.metric, X_indices=minibatch_indices)
  File "ibdistance\libdistance.pyx", line 129, in msmbuilder.libdistance.pdist (msmbuilder/libdistance\libdistance.cpp:2826)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_kmedoids.test_contigify_ids_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_kmedoids.py", line 48, in test_contigify_ids_1
    out, mapping = contigify_ids(inp)
  File "msmbuilder\cluster\_kmedoids.pyx", line 110, in msmbuilder.cluster._kmedoids.contigify_ids (msmbuilder/cluster\_kmedoids.cpp:2462)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_kmedoids.test_contigify_ids_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_kmedoids.py", line 58, in test_contigify_ids_2
    out, mapping = contigify_ids(inp)
  File "msmbuilder\cluster\_kmedoids.pyx", line 110, in msmbuilder.cluster._kmedoids.contigify_ids (msmbuilder/cluster\_kmedoids.cpp:2462)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_kmedoids.test_multitraj_cluster_ids_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_kmedoids.py", line 113, in test_multitraj_cluster_ids_2
    km.fit(trajs)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\minibatchkmedoids.py", line 197, in fit
    MultiSequenceClusterMixin.fit(self, sequences)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\base.py", line 48, in fit
    super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\cluster\minibatchkmedoids.py", line 110, in fit
    dmat = libdistance.pdist(X, metric=self.metric, X_indices=minibatch_indices)
  File "ibdistance\libdistance.pyx", line 129, in msmbuilder.libdistance.pdist (msmbuilder/libdistance\libdistance.cpp:2826)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: Failure: ValueError (Buffer dtype mismatch, expected 'npy_intp' but got 'long')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\loader.py", line 252, in generate
    for test in g():
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 62, in test_assign_nearest_float_double_2
    assignments, inertia = assign_nearest(X, Y, metric, X_indices)
  File "ibdistance\libdistance.pyx", line 77, in msmbuilder.libdistance.assign_nearest (msmbuilder/libdistance\libdistance.cpp:2251)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_libdistance.test_assign_nearest_rmsd_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 97, in test_assign_nearest_rmsd_2
    assignments, inertia = assign_nearest(X_rmsd, Y_rmsd, "rmsd", X_indices)
  File "ibdistance\libdistance.pyx", line 77, in msmbuilder.libdistance.assign_nearest (msmbuilder/libdistance\libdistance.cpp:2251)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: Failure: ValueError (Buffer dtype mismatch, expected 'npy_intp' but got 'long')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\loader.py", line 252, in generate
    for test in g():
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 131, in test_pdist_double_float_2
    pdist_1 = pdist(X, metric, X_indices=X_indices)
  File "ibdistance\libdistance.pyx", line 129, in msmbuilder.libdistance.pdist (msmbuilder/libdistance\libdistance.cpp:2826)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_libdistance.test_pdist_rmsd_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 147, in test_pdist_rmsd_2
    got = pdist(X_rmsd, "rmsd", X_indices)
  File "ibdistance\libdistance.pyx", line 129, in msmbuilder.libdistance.pdist (msmbuilder/libdistance\libdistance.cpp:2826)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: Failure: ValueError (Buffer dtype mismatch, expected 'npy_intp' but got 'long')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\loader.py", line 252, in generate
    for test in g():
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 172, in test_dist_double_float_2
    dist_1 = dist(X, Y[0], metric, X_indices)
  File "ibdistance\libdistance.pyx", line 176, in msmbuilder.libdistance.dist (msmbuilder/libdistance\libdistance.cpp:3334)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_libdistance.test_dist_rmsd_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 187, in test_dist_rmsd_2
    d = dist(X_rmsd, Y_rmsd[0], "rmsd", X_indices)
  File "ibdistance\libdistance.pyx", line 176, in msmbuilder.libdistance.dist (msmbuilder/libdistance\libdistance.cpp:3334)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_libdistance.test_sumdist_double_float
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 199, in test_sumdist_double_float
    sumdist(X, metric, pairs))
  File "ibdistance\libdistance.pyx", line 220, in msmbuilder.libdistance.sumdist (msmbuilder/libdistance\libdistance.cpp:3906)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_libdistance.test_sumdist_rmsd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 207, in test_sumdist_rmsd
    sumdist(X_rmsd, "rmsd", pairs),
  File "ibdistance\libdistance.pyx", line 220, in msmbuilder.libdistance.sumdist (msmbuilder/libdistance\libdistance.cpp:3906)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_libdistance.test_canberra_32_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_libdistance.py", line 241, in test_canberra_32_2
    assignments, inertia = assign_nearest(X, Y, 'canberra', X_indices=X_indices)
  File "ibdistance\libdistance.pyx", line 77, in msmbuilder.libdistance.assign_nearest (msmbuilder/libdistance\libdistance.cpp:2251)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_ratematrix.test_hessian_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_ratematrix.py", line 228, in test_hessian_1
    hessian1 = _ratematrix.hessian(theta, C)
  File "msmbuilder\msm\_ratematrix.pyx", line 428, in msmbuilder.msm._ratematrix.hessian (msmbuilder/msm\_ratematrix.c:9396)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
 
======================================================================
ERROR: msmbuilder.tests.test_workflows.test_workflow_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_workflows.py", line 32, in test_workflow_2
    subprocess.check_call(line.split())
  File "C:\Python34_64\envs\_test\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msmb', 'GaussianHMM', '--inp', 'atom_pairs_tica.h5', '--out', 'hmm.pkl', '--n_states', '2']' returned non-zero exit status 255
 
======================================================================
ERROR: msmbuilder.tests.test_workflows.test_workflow_3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_64\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win-amd64.egg\msmbuilder\tests\test_workflows.py", line 38, in test_workflow_3
    subprocess.check_call(line.split())
  File "C:\Python34_64\envs\_test\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msmb', 'RegularSpatial', '--inp', "'~/msmbuilder_data/alanine_dipeptide/*.dcd'", '--transformed', 'rs_rmsd.h5', '--metric', 'rmsd', '--top', '~/msmbuilder_data/alanine_dipeptide/ala2.pdb', '--d_min', '0.1']' returned non-zero exit status 1
```

**Comment by rmcgibbo** [comment]
latest appveyor job: https://ci.appveyor.com/project/rmcgibbo/msmbuilder/build/1.0.361

**Comment by rmcgibbo** [comment]
Okay, it's working--ish.

**Comment by jchodera** [comment]
Huzzah!
