### ISSUE TITLE
creating model based off of dihedral

### ISSUE THREAD

**Issue by akiikius** [msmbuilder/msmbuilder#592]
Hi,

I would like to perform a clustering using dihedrals as a metric. Is that possible?

How would i be able to do it using a command similar to this:

 msmb Cluster -o data-hybrid rmsd -a AtomIndices.dat hybrid -d 0.200 -l 50 

I tried substituting rmsd for dihedral but i get:
```
--------------------------------------------------------------------------------
{'alg': 'hybrid',
 'dihedral_angles': 'Atomindices2.dat',
 'dihedral_metric': 'euclidean',
 'dihedral_p': 2,
 'dihedral_userfilename': 'DihedralIndices.dat',
 'hybrid_distance_cutoff': 10.0,
 'hybrid_global_iters': 0,
 'hybrid_ignore_max_objective': False,
 'hybrid_local_num_iters': 50,
 'hybrid_num_clusters': None,
 'hybrid_too_close_cutoff': 0.0001,
 'metric': 'dihedral',
 'output_dir': 'data-hybrid',
 'project': 'ProjectInfo.yaml',
 'quiet': False,
 'stride': 1}
Traceback (most recent call last):
  File "/Users/stumusii/anaconda/envs/py27/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==2.8.2', 'console_scripts', 'msmb')()
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/scripts/msmb.py", line 51, in entry_point
    getattr(scripts, args.subparser_name).entry_point()
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/scripts/Cluster.py", line 287, in entry_point
    main(args, metric)
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/scripts/Cluster.py", line 242, in main
    ptrajs, which = load_prep_trajectories(project, args.stride, atom_indices, metric)
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/scripts/Cluster.py", line 132, in load_prep_trajectories
    ptrj_chunk = metric.prepare_trajectory(chunk)
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/metrics/dihedral.py", line 106, in prepare_trajectory
    dihedrals = np.hstack(f(e)(trajectory)[1] for e in self.angles.split('/'))
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/numpy/core/shape_base.py", line 272, in hstack
    arrs = [atleast_1d(_m) for _m in tup]
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/metrics/dihedral.py", line 106, in <genexpr>
    dihedrals = np.hstack(f(e)(trajectory)[1] for e in self.angles.split('/'))
  File "/Users/stumusii/anaconda/envs/py27/lib/python2.7/site-packages/msmbuilder-2.8.2-py2.7.egg/msmbuilder/metrics/dihedral.py", line 105, in <lambda>
    f = lambda e: getattr(_dihedralcalc, 'compute_%s' % e)
AttributeError: 'module' object has no attribute 'compute_Atomindices2.dat'
```
Thanks!

**Comment by rmcgibbo** [comment]
Your traceback is using an outdated version of msmbuilder (version 2.8). That code is available at https://github.com/msmbuilder/msmbuilder-legacy, but is not being actively maintained. The latest release of msmbuilder is version 3.2.
