### ISSUE TITLE
Python 3 test failures on windows

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#594]
There are still a couple failures on appveyor for python 3
```
======================================================================
ERROR: msmbuilder.tests.test_msm_uncertainty.test_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_32\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\tests\test_msm_uncertainty.py", line 61, in test_1
    print(model2.uncertainty_timescales())
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\msm\ratematrix.py", line 263, in uncertainty_timescales
    self._build_information()
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\msm\ratematrix.py", line 300, in _build_information
    self.information_[np.ix_(inds, inds)] = scipy.linalg.pinv(-hessian)
  File "C:\Python34_32\envs\_test\lib\site-packages\scipy\linalg\basic.py", line 602, in pinv
    a = np.asarray_chkfinite(a)
  File "C:\Python34_32\envs\_test\lib\site-packages\numpy\lib\function_base.py", line 613, in asarray_chkfinite
    "array must not contain infs or NaNs")
nose.proxy.ValueError: array must not contain infs or NaNs
-------------------- >> begin captured stdout << ---------------------
loading "C:\Users\appveyor\msmbuilder_data\doublewell\version-1_random-state-0.pkl"...
MSM uncertainty timescales:
[ 108.53833321    1.53644089    0.99740744    0.69777323    0.3952434
    0.35207525    0.29733261    0.20266253    0.13963238]
ContinuousTimeMSM uncertainty timescales:
[ 105.39363654    1.51931341    0.98284022    0.69910175    0.39404041
    0.36077648    0.30040502    0.20571821    0.14115993]
 
MSM uncertainty timescales:
[ 101.02181988    1.10618418    1.79733039    0.70170151    0.39851563
    0.36410131    0.1687596     0.20884279    0.2933363 ]
ContinuousTimeMSM uncertainty timescales:
[ 96.55023173   1.08389409   1.78869187   0.69803183   0.40388189
   0.36693775   0.17080523   0.21394565   0.29927035]
 
MSM uncertainty timescales:
[ 79.72932416   1.0923301    1.15537712   0.56568735   0.38333731
   0.24890267   0.19882026   0.12610325   0.2042072 ]
ContinuousTimeMSM uncertainty timescales:
 
--------------------- >> end captured stdout << ----------------------
 
======================================================================
ERROR: msmbuilder.tests.test_ratematrix.test_score_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_32\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\tests\test_ratematrix.py", line 403, in test_score_2
    assignments = cluster.fit_transform(ds)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\base.py", line 173, in fit_transform
    return self.fit_predict(sequences, y)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\base.py", line 154, in fit_predict
    labels = super(MultiSequenceClusterMixin, self).fit_predict(sequences)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\ndgrid.py", line 131, in fit_predict
    return self.fit(X).predict(X)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\base.py", line 48, in fit
    super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\ndgrid.py", line 78, in fit
    X = array2d(X)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\utils\validation.py", line 62, in array2d
    _assert_all_finite(X_2d)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\utils\validation.py", line 74, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
nose.proxy.ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
-------------------- >> begin captured stdout << ---------------------
Saving "C:\Users\appveyor\msmbuilder_data\muller\version-1_random-state-0.pkl"... (<class 'list'>)
 
--------------------- >> end captured stdout << ----------------------
 
======================================================================
ERROR: msmbuilder.tests.test_ratematrix.test_score_3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_32\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\tests\test_ratematrix.py", line 426, in test_score_3
    assignments = cluster.fit_transform(ds)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\base.py", line 173, in fit_transform
    return self.fit_predict(sequences, y)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\base.py", line 154, in fit_predict
    labels = super(MultiSequenceClusterMixin, self).fit_predict(sequences)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\ndgrid.py", line 131, in fit_predict
    return self.fit(X).predict(X)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\base.py", line 48, in fit
    super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\cluster\ndgrid.py", line 78, in fit
    X = array2d(X)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\utils\validation.py", line 62, in array2d
    _assert_all_finite(X_2d)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\utils\validation.py", line 74, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
nose.proxy.ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
-------------------- >> begin captured stdout << ---------------------
loading "C:\Users\appveyor\msmbuilder_data\muller\version-1_random-state-0.pkl"...
 
--------------------- >> end captured stdout << ----------------------
```

**Comment by rmcgibbo** [comment]
It looks like some of these (all?) come directly when loading the dataset,
which is odd. Can anyone reproduce?

**Comment by mpharrigan** [comment]
What do you mean? They come during fit_predict

**Comment by rmcgibbo** [comment]
Don't they come right at the beginning of fit_predict, when it's checking
the data? Maybe I misremembered.
