### ISSUE TITLE
MSMBuilder - AtomPairsFeaturizer error

### ISSUE THREAD

**Issue by mihirdate** [msmbuilder/msmbuilder#640]
Hi
I am trying to build MSM on my set of trajectories. Following is the error I get when I run it on dcd trajectories. It worked on .h5 files though. 
I also tried using --transformed in place of --out. The error message is same except "--out is deprecated warning."

```
$msmb AtomPairsFeaturizer --out pair_features --pair_indices AtomIndices.txt --top mini_complex-tip3.1.1-1.pdb --trjs "./*.dcd"
/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/commands/featurizer.py:44: UserWarning: --out is deprecated. Please use --transformed
  warnings.warn("--out is deprecated. Please use --transformed")
AtomPairsFeaturizer(exponent=1.0,
          pair_indices=array([[   4,   15],
       [   4,   30],
       ...,
       [5533, 5574],
       [5557, 5574]]),
          periodic=False)
An unexpected error has occurred with MSMBuilder (version 3.2.0), please                                                                                      |ETA:  0:00:00
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/opt/az/local/anaconda/2.3.0/installdir/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/commands/featurizer.py", line 66, in start
    for i, chunk in enumerate(input_dataset.iterload(key, chunk=self.chunk)):
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 478, in iterload
    traj = f.read_as_traj(topology, n_frames=chunk*stride, stride=stride, atom_indices=atom_indices, **kwargs)
  File "dcd.pyx", line 395, in dcd.DCDTrajectoryFile.read_as_traj (mdtraj/formats/dcd/dcd.c:4364)
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 1074, in __init__
    self.xyz = xyz
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 823, in xyz
    warn_on_cast=False, add_newaxis_on_deficient_ndim=True)
  File "/opt/az/local/anaconda/2.3.0/installdir/lib/python2.7/site-packages/mdtraj/utils/validation.py", line 148, in ensure_type
    raise error
ValueError: xyz must be shape (Any, 67058, 3). You supplied  (1280, 62319, 3)
```

Can you tell me if this is an issue of trajectory file format or anything else?

**Comment by mpharrigan** [comment]
Make sure your dcd files have the same number of atoms as your topology. The error indicates that the dcd's have 62319 atoms but it expected 67058 based on the topology
