### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#649]
```
======================================================================
ERROR: msmbuilder.tests.test_msm_uncertainty.test_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_32\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\tests\test_msm_uncertainty.py", line 61, in test_1
    print(model2.uncertainty_timescales())
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\msm\ratematrix.py", line 278, in uncertainty_timescales
    self._build_information()
  File "c:\python34_32\envs\_test\lib\site-packages\msmbuilder-3.3.0.dev0-py3.4-win32.egg\msmbuilder\msm\ratematrix.py", line 324, in _build_information
    self.information_[np.ix_(inds, inds)] = scipy.linalg.pinv(-hessian)
  File "C:\Python34_32\envs\_test\lib\site-packages\scipy\linalg\basic.py", line 889, in pinv
    a = _asarray_validated(a, check_finite=check_finite)
  File "C:\Python34_32\envs\_test\lib\site-packages\scipy\_lib\_util.py", line 135, in _asarray_validated
    a = np.asarray_chkfinite(a)
  File "C:\Python34_32\envs\_test\lib\site-packages\numpy\lib\function_base.py", line 613, in asarray_chkfinite
    "array must not contain infs or NaNs")
nose.proxy.ValueError: array must not contain infs or NaNs
-------------------- >> begin captured stdout << ---------------------
loading "C:\Users\appveyor\msmbuilder_data\doublewell\version-1_random-state-0.pkl"...
MSM uncertainty timescales:
[ 108.53833321    1.53644089    0.99740744    0.69777323    0.3952434
    0.35207525    0.29733261    0.20266253    0.13963238]
ContinuousTimeMSM uncertainty timescales:
 
--------------------- >> end captured stdout << ----------------------
 
```

Seems to happen on all 4 platforms

**Comment by mpharrigan** [comment]
https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/msm/_ratematrix.pyx#L449

`w` has a zero element after this line. This turns into a 0 in `T` and nans when dividing by entries in `T`

Changing the random seed used in the test makes it go away

@rmcgibbo thoughts?

**Comment by rmcgibbo** [comment]
One of the eigenvalues is exactly zero?
