### ISSUE TITLE
Memory error using command line msmb AtomPairsFeaturizer

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#662]
Hi eveyone, 

I've encountered the following error when trying to apply the same commands as the command line tutorial http://msmbuilder.org/latest/commandline.html on my data (larger than the alanine-dipeptide)
```
Traceback (most recent call last):
  File "/home/je714/anaconda3/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/home/je714/anaconda3/lib/python3.4/site-packages/msmbuilder-3.3.0-py3.4-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/home/je714/anaconda3/lib/python3.4/site-packages/msmbuilder-3.3.0-py3.4-linux-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/home/je714/anaconda3/lib/python3.4/site-packages/msmbuilder-3.3.0-py3.4-linux-x86_64.egg/msmbuilder/commands/featurizer.py", line 62, in start
    trajectory.append(self.instance.partial_transform(chunk))
  File "/home/je714/anaconda3/lib/python3.4/site-packages/msmbuilder-3.3.0-py3.4-linux-x86_64.egg/msmbuilder/featurizer/featurizer.py", line 250, in partial_transform
    d = md.geometry.compute_distances(traj, self.pair_indices, periodic=self.periodic)
  File "/home/je714/anaconda3/lib/python3.4/site-packages/mdtraj/geometry/distance.py", line 84, in compute_distances
    out = np.empty((xyz.shape[0], pairs.shape[0]), dtype=np.float32)
MemoryError
```
Is the command line only suitable for small subsets of MD data? I've tried feeding the same MD data with one big file or in different chunks, makes no difference. Actually this is only a small subset of my complete dataset, is my only option to use the python API and mdtraj's iterload? For quick trials the command line is actually more suitable... 

Thanks in advance

Edit: Forgot to say I'm using MSMBuilder (version 3.3.0)

**Comment by jeiros** [comment]
I also tried setting --chunk to 100 instead of the default 10000 but I'm still getting a Memory Error. It works setting a stride of 100 though. Sorry for raising an issue, not a bug, just I don't have enough memory apparently.

**Comment by jeiros** [comment]
Sorry for the triple post... 
I'm getting similar memory errors when performing tICA on the dataset obtained from AtomPairsFeaturizer using a 1000 frame stride. The atom_pairs.pkl file is 87M big and the 00000000.npy file in the atom_pairs folder is 479M. 
In the tICA help page I don't see any flag to aid for data processing in chunks to save memory. Any idea on how to proceed?

**Comment by mpharrigan** [comment]
The number of atom pairs features increases combinatorically with number of atoms. Use a different featurizer like `DihedralFeaturizer`.

We probably shouldn't use atom pairs featurizer in the tutorial, but using dihedrals on alanine dipeptide is really boring
