### ISSUE TITLE
Error during clustering

### ISSUE THREAD

**Issue by imanp** [msmbuilder/msmbuilder#669]
Got this error after clustering. 
Featurizer used: SuperposeFeaturizer.

What does the ValueError in the next last line mean? Did i do something inproper during featurization?  

```
squirrel:lacy-TDG iman$ msmb KCenters --n_clusters=300 -i superpose_features -t clustering 
KCenters(metric='euclidean', n_clusters=300, random_state=None)
Fitting model...
*********
*RESULTS*
*********
KCenters clustering
--------------------
n_clusters : 300
metric     : euclidean

Inertia       : 1207.39492081
Mean distance : 0.167298728115
Max  distance : 0.228090495021

--------------------------------------------------------------------------------
An unexpected error has occurred with MSMBuilder (version 3.3.0), please#########################################|ETA:  0:00:00
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/Users/iman/anaconda/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/Users/iman/anaconda/lib/python2.7/site-packages/msmbuilder-3.3.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/Users/iman/anaconda/lib/python2.7/site-packages/msmbuilder-3.3.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/Users/iman/anaconda/lib/python2.7/site-packages/msmbuilder-3.3.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/commands/fit_transform.py", line 72, in start
    out_ds[key] = self.instance.partial_transform(in_seq)
  File "/Users/iman/anaconda/lib/python2.7/site-packages/msmbuilder-3.3.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/cluster/base.py", line 169, in partial_transform
    return self.partial_predict(X)
  File "/Users/iman/anaconda/lib/python2.7/site-packages/msmbuilder-3.3.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/cluster/base.py", line 135, in partial_predict
    return super(MultiSequenceClusterMixin, self).predict(X)
  File "/Users/iman/anaconda/lib/python2.7/site-packages/msmbuilder-3.3.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/cluster/kcenters.py", line 119, in predict
    X, self.cluster_centers_, metric=self.metric)
  File "msmbuilder/libdistance/libdistance.pyx", line 124, in msmbuilder.libdistance.assign_nearest (msmbuilder/libdistance/libdistance.cpp:2799)
  File "stringsource", line 616, in View.MemoryView.memoryview_cwrapper (msmbuilder/libdistance/libdistance.cpp:17211)
  File "stringsource", line 323, in View.MemoryView.memoryview.__cinit__ (msmbuilder/libdistance/libdistance.cpp:13580)
ValueError: ndarray is not C-contiguous
Closing remaining open files:clustering.h5...done
```

**Comment by mpharrigan** [comment]
I haven't seen that before. Maybe @rmcgibbo will know. It looks like its failing in libdistance.

Can you try it with another clustering algorithm i.e `MiniBatchKMeans`

Aside: KCenters provides a pretty poor clustering of the data. Is there a reason why you want to use it specifically?

**Comment by imanp** [comment]
I tried with the hybrid k medoids clustering also. Got the same result. Will try MiniBatchKMeans.

Im not sure if it my data that is causing the error. I used the superposefeaturizer to analyze the movement of one molecule.

But it was difficult to understand from the error message as it is an Exception. If needed i can provide a patch after that we have troubleshooted the issue

**Comment by mpharrigan** [comment]
Let me know if minibatchkmeans works

If that doesn't work, paste the complete set of commands you used to generate the data
