### ISSUE TITLE
problem in fitting kinetic model tICA

### ISSUE THREAD

**Issue by aditya-kr-sarkar** [msmbuilder/msmbuilder#698]
Respected Sir/Mam,

I am new to MSMbuilder. I have just installed it (msmbuilder 3.3.1) in Ubuntu 14.0 64bit following instructions given in http://msmbuilder.org/3.3.0/installation.html, using conda. When I am trying the "AlanineDipeptide" tutorial given in "Command Line Tutorial" I have found following message during "tICA" model fitting using this command: 
msmb tICA -i pair_features --out tica_model --transformed tica_trajs --n_components 4
and the message is following:
```
-------------------------------------
tICA(gamma=0.05, lag_time=1, n_components=4, weighted_transform=False)
Fitting model...
*********
*RESULTS*
*********
An unexpected error has occurred with MSMBuilder (version 3.3.1), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/home/aditya/applications/anaconda2/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/commands/fit_transform.py", line 61, in start
    print(self.instance.summarize())
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/decomposition/tica.py", line 446, in summarize
    timescales=self.timescales_[:5], eigenvalues=self.eigenvalues_[:5])
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/decomposition/tica.py", line 208, in timescales_
    self._solve()
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/decomposition/tica.py", line 168, in _solve
    if not np.allclose(self.offset_correlation_, self.offset_correlation_.T):
  File "/home/aditya/applications/anaconda2/lib/python2.7/site-packages/msmbuilder/decomposition/tica.py", line 223, in offset_correlation_
    two_N = 2 * (self.n_observations_ - self.lag_time * self.n_sequences_)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

I am unable to resolve this issue so seeking help from you.

**Comment by dodo5575** [comment]
I had the same issue on my mac. But I found the reason is that the command line tutorial is not updated. 
#657
After I change my previous command to 
msmb AtomPairsFeaturizer --transformed pair_features     --pair_indices AtomIndices.txt     --top alanine_dipeptide/ala2.pdb     --trjs "alanine_dipeptide/*.dcd"
Then, it works for me.

**Comment by aditya-kr-sarkar** [comment]
Thank you very much. Now it works.
One more request, how do I get the manual of MSMbuilder?

**Comment by rmcgibbo** [comment]
The manual is on the web at msmbuilder.org.

**Comment by aditya-kr-sarkar** [comment]
Thank you very much
