### ISSUE TITLE
msmb in command line: AttributeError: 'unicode' object has no attribute 'version'

### ISSUE THREAD

**Issue by dodo5575** [msmbuilder/msmbuilder#699]
I have msmbuilder 3.3.1 np110py27_0 in my mac. When I tried to run msmb from the terminal, it returned following error. Any help would be appreciated!
```
[0]~/Desktop/msmb_tutorial /Applications/anaconda/bin/msmb
Traceback (most recent call last):
  File "/Applications/anaconda/bin/msmb", line 4, in <module>
    from msmbuilder.scripts.msmb import main
  File "/Applications/anaconda/lib/python2.7/site-packages/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/Applications/anaconda/lib/python2.7/site-packages/msmbuilder/commands/__init__.py", line 10, in <module>
    from .implied_timescales import ImpliedTimescales
  File "/Applications/anaconda/lib/python2.7/site-packages/msmbuilder/commands/implied_timescales.py", line 29, in <module>
    import pandas as pd
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 44, in <module>
    from pandas.core.api import *
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 17, in <module>
    from pandas.core.frame import DataFrame
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 41, in <module>
    from pandas.core.series import Series
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/core/series.py", line 2909, in <module>
    import pandas.tools.plotting as _gfx
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/tools/plotting.py", line 135, in <module>
    if _mpl_ge_1_5_0():
  File "/Applications/anaconda/lib/python2.7/site-packages/pandas/tools/plotting.py", line 130, in _mpl_ge_1_5_0
    return (matplotlib.__version__  >= LooseVersion('1.5')
  File "/Applications/anaconda/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'unicode' object has no attribute 'version'
```

**Comment by rmcgibbo** [comment]
From the traceback, this looks like a problem with `pandas` and `matplotlib` not working together properly. To confirm, do you get the same error if you simply execute `python -c "import pandas"` on the command line?

**Comment by rmcgibbo** [comment]
Same error on stackoverflow. http://stackoverflow.com/questions/33159634/pandas-v0-17-0-attributeerror-unicode-object-has-no-attribute-version. I suspect `conda update matplotlib` will fix the problem.

**Comment by dodo5575** [comment]
Yes. That's it. Thank you very much!!
