### ISSUE TITLE
"Eigenvalue range specified is not valid" ValueError when runnning tICA via command line

### ISSUE THREAD

**Issue by xaviermartinez2012** [msmbuilder/msmbuilder#824]
Hello,
I came across an issue when running tICA on a MD dataset.

command: 
```
msmb tICA -i LUTEO_DihedralFeatures/ --out LUTEO_DihedralFeatures_tICA_1000 --transformed LUTEO_DihedralFeatures_tICA_1000.h5 --n_components 1000
```

Note: I chose 1000 as a test...

The original dataset is a collection of about ~16,000 ".xtc" trajectory files (about ~1,000,000 conformations). I then ran "msmb DihedralFeaturizer" to obtain the "LUTEO_DihedralFeatures/" dataset.

Contents of "LUTEO_DihedralFeatures/":
000000.npy - 00016274.npy files. 

Error:

```
tICA(kinetic_mapping=False, lag_time=1, n_components=1000, shrinkage=None,
   weighted_transform=False)
Fitting model...
*********
*RESULTS*
*********
An unexpected error has occurred with MSMBuilder (version 3.4.0), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/usr/local/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==3.4.0', 'console_scripts', 'msmb')()
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder/cmdline.py", line 461, in start
    instance.start()
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder/commands/fit_transform.py", line 61, in start
    print(self.instance.summarize())
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder/decomposition/tica.py", line 475, in summarize
    kinetic_mapping=self.kinetic_mapping, timescales=self.timescales_[:5],
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder/decomposition/tica.py", line 215, in timescales_
    self._solve()
  File "/usr/local/lib/python2.7/dist-packages/msmbuilder/decomposition/tica.py", line 183, in _solve
    eigvals=(self.n_features-self.n_components, self.n_features-1))
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/decomp.py", line 329, in eigh
    'Valid range is [%s,%s]' % (0, a1.shape[0]-1))
ValueError: The eigenvalue range specified is not valid.
Valid range is [0,-1]
```

**Comment by mpharrigan** [comment]
How many dihedral features do you have? If less than 1000, I can see this being a problem. tICA is typically used to find a small number (~2-20) of kinetically motivated features from a large number of structural features

**Comment by xaviermartinez2012** [comment]
Thank you for the response. Based on this, I think I used tICA incorrectly with my dataset and moved on to a more suitable algorithm.
