### ISSUE TITLE
python setup.py develop breaks msmb

### ISSUE THREAD

**Issue by brookehus** [msmbuilder/msmbuilder#872]
When I run `install` everything is fine, but running `python setup.py develop` gives:

```
[brooke@zelda:~/source/msmbuilder (ward-msmb)]$ msmb LandmarkAgglomerative -h
Traceback (most recent call last):
  File "/Users/brooke/anaconda/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder', 'console_scripts', 'msmb')()
  File "/Users/brooke/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "/Users/brooke/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/Users/brooke/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 2202, in load
  File "/Users/brooke/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 2208, in resolve
  File "/Users/brooke/source/msmbuilder/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/Users/brooke/source/msmbuilder/msmbuilder/commands/__init__.py", line 8, in <module>
    from .fit_transform import KMeansCommand, KCentersCommand, LandmarkAgglomerativeCommand
  File "/Users/brooke/source/msmbuilder/msmbuilder/commands/fit_transform.py", line 18, in <module>
    from ..decomposition import tICA, PCA, SparseTICA
  File "/Users/brooke/source/msmbuilder/msmbuilder/decomposition/__init__.py", line 6, in <module>
    from .ktica import KernelTICA
  File "/Users/brooke/source/msmbuilder/msmbuilder/decomposition/ktica.py", line 101
SyntaxError: Non-ASCII character '\xe2' in file /Users/brooke/source/msmbuilder/msmbuilder/decomposition/ktica.py on line 102, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by cxhernandez** [comment]
This is on master?

**Comment by brookehus** [comment]
Yeah I could reproduce it on master. My branch didn't go anywhere near ktica.

**Comment by cxhernandez** [comment]
Hmm. I don't see that character in `ktica.py`. Are you sure you've merged the latest changes on the master branch?

btw I'm using the following code to check for `\xe2`:

```python
 with open("msmbuilder/decomposition/ktica.py") as fp:
     for i, line in enumerate(fp):
         if "\xe2" in line:
             print('hi')
```

**Comment by mpharrigan** [comment]
https://github.com/msmbuilder/msmbuilder/commit/0f52fb832a360f5d8077c18f283d8a63815bcff2
