### ISSUE TITLE
Issues with sklearn.cluster in scikit-learn 0.18 (but not 0.17)

### ISSUE THREAD

**Issue by jchodera** [msmbuilder/msmbuilder#922]
On `python 3.5` with the latest `msmbuilder 3.6.0`, I saw the following error with the latest `scikit-learn 0.18` installed by default:
```
mski1776:cholera choderaj$ python cluster_tica.py 
/Users/choderaj/miniconda3/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/choderaj/miniconda3/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/choderaj/miniconda3/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/choderaj/miniconda3/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Traceback (most recent call last):
  File "cluster_tica.py", line 45, in <module>
    import msmbuilder.cluster
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/msmbuilder/cluster/__init__.py", line 82, in <module>
    class GMM(MultiSequenceClusterMixin, mixture.GMM, BaseEstimator):
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/msmbuilder/cluster/__init__.py", line 83, in GMM
    __doc__ = _replace_labels(mixture.GMM.__doc__)
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/msmbuilder/cluster/__init__.py", line 35, in _replace_labels
    lines = doc.splitlines()
```
Downgrading to `scikit-learn 0.17` fixed the issue.

**Comment by mpharrigan** [comment]
cc #915

**Comment by jchodera** [comment]
Thanks!
