### ISSUE TITLE
symlink problems

### ISSUE THREAD

**Issue by DanaNew** [msmbuilder/msmbuilder#923]
Dear all,
I installed msmb as it's written in tutorial and tried to explore example, but faced with problem attached. I checked symlinks, they are not broken (when I press on top.pdb it opens wright structure in DSViewer). I tried to change symlinks and wrote the whole way to files but obtained the same error... What have I to do to fix problem? Thank you so much

(O:\Program Files\miniconda) O:\phd\mgf\test_msmb\analysis>python gather-metadat
a.py
Traceback (most recent call last):
  File "O:\Program Files\miniconda\lib\site-packages\pandas\indexes\base.py", li
ne 1945, in get_loc
    return self._engine.get_loc(key)
  File "pandas\index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas
\index.c:4154)
  File "pandas\index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas
\index.c:4018)
  File "pandas\hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.g
et_item (pandas\hashtable.c:12368)
  File "pandas\hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.g
et_item (pandas\hashtable.c:12322)
KeyError: 'run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gather-metadata.py", line 18, in <module>
    meta = gather_metadata("trajs/*.xtc", parser)
  File "O:\Program Files\miniconda\lib\site-packages\msmbuilder\io\gather_metada
ta.py", line 204, in gather_metadata
    return meta.set_index(parser.index).sort_index()
  File "O:\Program Files\miniconda\lib\site-packages\pandas\core\frame.py", line
 2837, in set_index
    level = frame[col]._values
  File "O:\Program Files\miniconda\lib\site-packages\pandas\core\frame.py", line
 1997, in __getitem__
    return self._getitem_column(key)
  File "O:\Program Files\miniconda\lib\site-packages\pandas\core\frame.py", line
 2004, in _getitem_column
    return self._get_item_cache(key)
  File "O:\Program Files\miniconda\lib\site-packages\pandas\core\generic.py", li
ne 1350, in _get_item_cache
    values = self._data.get(item)
  File "O:\Program Files\miniconda\lib\site-packages\pandas\core\internals.py",
line 3290, in get
    loc = self.items.get_loc(item)
  File "O:\Program Files\miniconda\lib\site-packages\pandas\indexes\base.py", li
ne 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas
\index.c:4154)
  File "pandas\index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas
\index.c:4018)
  File "pandas\hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.g
et_item (pandas\hashtable.c:12368)
  File "pandas\hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.g
et_item (pandas\hashtable.c:12322)
KeyError: 'run'

**Comment by mpharrigan** [comment]
Hi,
We (the developers) typically work on mac os or linux, which have great support for symlinks. You may run into problems running the tutorial on windows. You can (1) modify the scripts to use relative paths

```python
from msmbuilder.io import gather_metadata, save_meta, NumberedRunsParser
parser = NumberedRunsParser(
    traj_fmt="trajectory-{run}.xtc",
    top_fn="../top.pdb", # was "top.pdb"
    step_ps=50,
)
meta = gather_metadata("../trajs/*.xtc", parser) # was "trajs/*.xtc"
save_meta(meta)
```

or (2) avoid using the `msmb ProjectTemplate` feature. See http://msmbuilder.org/3.6.0/examples/index.html for examples that work cross-platform

**Comment by DanaNew** [comment]
It works!!! Oh, thank you so much)

**Comment by mpharrigan** [comment]
You'll probably have to modify each of the generated scripts in a similar way

**Comment by DanaNew** [comment]
Yes, you are right. I'll better try to use ubuntu, I think.
