### ISSUE TITLE
Fix sklean 0.18 failing test

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#926]
Can someone try to debug the test failure in sklearn 0.18

```
======================================================================
ERROR: msmbuilder.tests.test_featurizer_subset.test_that_all_featurizers_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/msmbuilder-3.7.0.dev0-py3.5-linux-x86_64.egg/msmbuilder/tests/test_featurizer_subset.py", line 77, in test_that_all_featurizers_run
    X_all = featurizer.transform(trajectories)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/msmbuilder-3.7.0.dev0-py3.5-linux-x86_64.egg/msmbuilder/featurizer/featurizer.py", line 1354, in transform
    for name, trans in self.transformer_list)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 322, in __init__
    self.results = batch()
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/sklearn/pipeline.py", line 570, in _transform_one
    res = transformer.transform(X)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1476298884112/_t_env/lib/python3.5/site-packages/msmbuilder-3.7.0.dev0-py3.5-linux-x86_64.egg/msmbuilder/featurizer/featurizer.py", line 159, in transform
    return [self.partial_transform(traj) for traj in traj_list]
TypeError: 'NoneType' object is not iterable
```

See also #918

**Comment by cxhernandez** [comment]
Here's the traceback I get locally (on Sherlock):

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4b61ebcf94cd> in <module>()
     18 featurizer.subsets = [np.arange(1) for i in range(featurizer.n_featurizers)]
     19
---> 20 X_all = featurizer.transform(trajectories)

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/msmbuilder/featurizer/featurizer.py in transform(self, traj_list)
   1352             delayed(sklearn.pipeline._transform_one)(trans, name, traj_list,
   1353                                                      self.transformer_weights)
-> 1354             for name, trans in self.transformer_list)
   1355
   1356         X_i_stacked = [np.hstack([Xs[feature_ind][trj_ind]

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    756             # was dispatched. In particular this covers the edge
    757             # case of Parallel used with an exhausted iterator.
--> 758             while self.dispatch_one_batch(iterator):
    759                 self._iterating = True
    760             else:

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    606                 return False
    607             else:
--> 608                 self._dispatch(tasks)
    609                 return True
    610

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    569         dispatch_timestamp = time.time()
    570         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 571         job = self._backend.apply_async(batch, callback=cb)
    572         self._jobs.append(job)
    573

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    107     def apply_async(self, func, callback=None):
    108         """Schedule a func to be run"""
--> 109         result = ImmediateResult(func)
    110         if callback:
    111             callback(result)

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    320         # Don't delay the application, to avoid keeping the input
    321         # arguments in memory
--> 322         self.results = batch()
    323
    324     def get(self):

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    129
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132
    133     def __len__(self):

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    129
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132
    133     def __len__(self):

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/sklearn/pipeline.py in _transform_one(transformer, name, weight, X)
    568
    569 def _transform_one(transformer, name, weight, X):
--> 570     res = transformer.transform(X)
    571     # if we have a weight for this transformer, multiply output
    572     if weight is None:

/home/cxh/anaconda/envs/msmb-dev/lib/python3.5/site-packages/msmbuilder/featurizer/featurizer.py in transform(self, traj_list, y)
    157             (n_samples_i, n_features)
    158         """
--> 159         return [self.partial_transform(traj) for traj in traj_list]
    160
    161     def describe_features(self, traj):

TypeError: 'NoneType' object is not iterable
```

**Comment by cxhernandez** [comment]
The only thing that stands out to me so far is that `self.transformer_weights` is `None`.

**Comment by mpharrigan** [comment]
```python
sklearn/pipeline.py in _transform_one(transformer, name, weight, X)
```
vs
```python
delayed(sklearn.pipeline._transform_one)(trans, name, traj_list, self.transformer_weights)
```

@cxhernandez told me this in person, but now I can see it clearly in the traceback. They must have changed the signature for `_transform_one`. We shouldn't be using an internal function like this, because they might change the signature!
