### ISSUE TITLE
msmb -h failed: AttributeError: module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by yongwangCPH** [msmbuilder/msmbuilder#956]
I am trying to use msmbuilder in MacOS10.12, but failed at the first step to run msmb -h. The errors are:

```
/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Traceback (most recent call last):
  File "/Users/yongwang/Work/HTMD/miniconda3/bin/msmb", line 4, in <module>
    import msmbuilder.scripts.msmb
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/msmbuilder/commands/__init__.py", line 24, in <module>
    from .fit_transform import (tICACommand, ButterworthCommand, DoubleEWMACommand,
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/msmbuilder/commands/fit_transform.py", line 24, in <module>
    from ..preprocessing import Butterworth, DoubleEWMA
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/msmbuilder/preprocessing/__init__.py", line 12, in <module>
    from .timeseries import Butterworth, EWMA, DoubleEWMA
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/msmbuilder/preprocessing/timeseries.py", line 3, in <module>
    from pandas import DataFrame
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/pandas/core/groupby.py", line 40, in <module>
    from pandas.core.frame import DataFrame
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 72, in <module>
    from pandas.core.series import Series
  File "/Users/yongwang/Work/HTMD/miniconda3/lib/python3.5/site-packages/pandas/core/series.py", line 51, in <module>
    import pandas.core.strings as strings
AttributeError: module 'pandas' has no attribute 'core'
```

I searched previous issues, but didn't find a solution ("conda update matplotlib" didn't help). Anyone could help? Thanks.

matplotlib                1.5.3               np111py35_1

**Comment by brookehus** [comment]
I found several people who have the same error message on stackoverflow by searching for the `AttributeError` in the last line of your output on google. This [post](https://forgetfulelephantblog.wordpress.com/2016/02/23/the-root-of-the-problem/) might also help. Please update with more information if you can't solve your problem after investigating these sources.

**Comment by rmcgibbo** [comment]
I would recommend that you uninstall and then reinstall `pandas` using `conda`.

**Comment by yongwangCPH** [comment]
Thank you for your suggestions. Actually, I googled a lot for the solutions (e.g. pip install -U matplotlib, or set the LANG), but all failed. I also tried to uninstall and reinstall pandas and msmbuilder, but still got the same errors. 

OS: MacOS Sierra, 10.12.1
MSM version: 3.6.1
pandas version: 0.19.2
 
Just let me know any specific information you need to debug. Thanks a lot!

**Comment by brookehus** [comment]
Try opening python and importing pandas and matplotlib and diagnosing the error messages. You could also create a virtual environment and try everything from scratch and see what happens. However, this is not an MSMBuilder problem, so I am closing the issue.
