### ISSUE TITLE
test_msm_uncertainty.test_doublewell fails

### ISSUE THREAD

**Issue by brookehus** [msmbuilder/msmbuilder#959]
only on Travis, with the numpy 1.11 builds (from personal experience).

**Comment by brookehus** [comment]
```
ERROR: msmbuilder.tests.test_msm_uncertainty.test_doublewell
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/msmbuilder-3.7.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/tests/test_msm_uncertainty.py", line 61, in test_doublewell
    print(model2.uncertainty_timescales())
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/msmbuilder-3.7.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/ratematrix.py", line 262, in uncertainty_timescales
    self._build_information()
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/msmbuilder-3.7.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/ratematrix.py", line 308, in _build_information
    self.information_[np.ix_(inds, inds)] = scipy.linalg.pinv(-hessian)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/scipy/linalg/basic.py", line 972, in pinv
    a = _asarray_validated(a, check_finite=check_finite)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/scipy/_lib/_util.py", line 228, in _asarray_validated
    a = toarray(a)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1485208320234/_t_env/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1033, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by cxhernandez** [comment]
addressed in https://github.com/msmbuilder/msmbuilder/pull/958
