### ISSUE TITLE
pandas error in plotting

### ISSUE THREAD

**Issue by MTZimmer** [msmbuilder/msmbuilder#968]
I am attempting to run through the [tutorial ](http://msmbuilder.org/3.7.0/tutorial.html) to ensure that MSMBuilder is working as expected. However, I have run into an error that I have been unable to resolve. I am working in linux and the first 5 steps in the tutorial executed as expected. When I tried to produce the metadata plot (paths were simplified with "..."):

$ python gather-metadata-plot.py
Traceback (most recent call last):
  File "gather-metadata-plot.py", line 68, in <module>
    plot_lengths(ax)
  File "gather-metadata-plot.py", line 26, in plot_lengths
    ax.hist(lengths_ns)
  File "/.../python/2.7.10/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5604, in hist
    if isinstance(x, np.ndarray) or not iterable(x[0]):
  File "/.../python/2.7.10/lib/python2.7/site-packages/pandas/core/series.py", line 583, in __getitem__
    result = self.index.get_value(self, key)
  File "/.../python/2.7.10/lib/python2.7/site-packages/pandas/indexes/base.py", line 1980, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/index.pyx", line 103, in pandas.index.IndexEngine.get_value (pandas/index.c:3332)
  File "pandas/index.pyx", line 111, in pandas.index.IndexEngine.get_value (pandas/index.c:3035)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 303, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6610)
  File "pandas/hashtable.pyx", line 309, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6554)
KeyError: 0

Any direction on pandas version or other requirements would be appreciated.

Sincerely,

**Comment by MTZimmer** [comment]
Minor update: I have pandas version 0.18.1

**Comment by brookehus** [comment]
Hey Max,

The tutorial runs fine for me and here are some of the package versions I have. Can you create a virtualenv and see if it works for you? If so, can you let us know whether your bug comes from an older version or a newer version?

```
msmbuilder==3.8.0.dev0
numpy==1.11.0
mdtraj==1.7.2
scipy==0.17.1
pandas==0.19.0
six==1.10.0
scikit-learn==0.18
numpydoc==0.5
matplotlib==1.5.1
```

**Comment by MTZimmer** [comment]
Thank you, brookehus. I have made a virtual environment with those packages.

I can now get to the featurize section of the tutorial. I also had to install multiprocessing and Pool.

And got a new error:
$ python featurize.py

Traceback (most recent call last):
  File "featurize.py", line 30, in <module>
    with Pool() as pool:
AttributeError: __exit__

This appears to have a known solution:
http://stackoverflow.com/questions/7447284/how-to-troubleshoot-an-attributeerror-exit-in-multiproccesing-in-python

I tried the following change to featurize.py:
#with Pool() as pool:
#    dihed_trajs = dict(pool.imap_unordered(feat, meta.iterrows()))
dihed_trajs = dict( Pool().imap_unordered(feat, meta.iterrows()))

but now get an error in saving the features:
Traceback (most recent call last):
  File "featurize.py", line 35, in <module>
    save_trajs(dihed_trajs, 'ftrajs', meta)
  File "/data5/bsi/bictools/lib/python/2.7.10/lib/python2.7/site-packages/msmbuilder/io/io.py", line 299, in save_trajs
    os.makedirs(os.path.dirname(npy_fn), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

Any assistance you or others can provide would be appreciated. Thank you,

**Comment by cxhernandez** [comment]
Hey @MTZimmer,

I noticed you're using Python 2.7. Is that necessary for your workflow? If not, it might be worth upgrading to Python 3.4+.

**Comment by mpharrigan** [comment]
The tutorial requires python 3.4+

**Comment by MTZimmer** [comment]
Thank you, @cxhernandez and @mpharrigan. I was using py2.7 because that's what I've typically used per older tool's requirements. Changing to py3.5 did solve these issues. Note that the MSMBuilder tutorial does not state that it requires py3.4+; consider adding a note about it.

I did get some warnings about deprecated sklearn functions. 
```
/...../python/3.5.2/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
```

In the end, I get a slightly different MSM microstates plot than the tutorial shows: [msm-microstates.pdf](https://github.com/msmbuilder/msmbuilder/files/800437/msm-microstates.pdf)
Should this be concerning, or would you attribute it to altered behaviors of the deprecated sklearn functions since the tutorial was built?

**Comment by cxhernandez** [comment]
>  Note that the MSMBuilder tutorial does not state that it requires py3.4+; consider adding a note about it.

Good point!

> Should this be concerning, or would you attribute it to altered behaviors of the deprecated sklearn functions since the tutorial was built?

My guess is that this is probably due to KMeans clustering results being non-deterministic. But maybe @mpharrigan knows better.

**Comment by mpharrigan** [comment]
Yeah clustering is random.

Thought there was a note about py3! will add one
